############# English navigation ##############

# main menu
[[main]]
parent = "Company"
name = "About Us"
url = "about-us/"
weight = 2

[[main]]
parent = "Solutions"
name = "Sales"
url = "solutions-sales/"
weight = 3

[[main]]
parent = "Services"
weight = 4
name = "Consulting"

[[main]]
parent = "Resources"
name = "Blog"
url = "blog/"

[[main]]
parent = "Company"
name = "Contact"
url = "contact/"

[[main]]
parent = "Company"
name = "Careers"
url = "careers/"


[[main]]
parent = "Resources"
name = "Authors"
url = "authors/"


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Resources"
url = "resources/"
weight = 2

[[footer]]
name = "Careers"
url = "careers/"
weight = 3
