############# English navigation ##############

# main menu
[[main]]
parent = "Solutions"
name = "Sales"
url = "solutions-sales/"
weight = 2

[[main]]
parent = "Solutions"
name = "E-commerce"
url = "solutions-e-commerce/"
weight = 2

[[main]]
parent = "Solutions"
name = "Healthcare"
url = "solutions-healthcare/"
weight = 2

[[main]]
parent = "Solutions"
name = "Finance"
url = "solutions-finance/"
weight = 2

[[main]]
parent = "Solutions"
name = "Real Estate"
url = "solutions-real-estate/"
weight = 2

[[main]]
parent = "Solutions"
name = "Retail"
url = "solutions-retail/"
weight = 2

[[main]]
parent = "Solutions"
name = "Travel"
url = "solutions-travel/"
weight = 2

[[main]]
parent = "Solutions"
name = "Governance"
url = "solutions-governance/"
weight = 2


[[main]]
parent = "Solutions"
name = "Energy"
url = "solutions-energy/"
weight = 2


[[main]]
parent = "Solutions"
name = "Support"
url = "solutions-support/"
weight = 2


[[main]]
parent = "Solutions"
name = "Advertising"
url = "solutions-advertising/"
weight = 2


[[main]]
parent = "Solutions"
name = "Telecom"
url = "solutions-telecom/"
weight = 2

[[main]]
parent = "Solutions"
name = "Fashion"
url = "solutions-fashion/"
weight = 2

[[main]]
parent = "Solutions"
name = "Human Resources"
url = "solutions-hr/"
weight = 2

[[main]]
parent = "Solutions"
name = "Manufacturing"
url = "solutions-manufacturing/"
weight = 2

[[main]]
parent = "Solutions"
name = "Education"
url = "solutions-education/"
weight = 2

[[main]]
parent = "Services"
weight = 1
name = "Consulting"

[[main]]
name = "Blog"
url = "blog/"
weight = 6

[[main]]
name = "About Us"
url = "about"
weight = 4

# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Resources"
url = "resources/"
weight = 2

[[footer]]
name = "Careers"
url = "careers/"
weight = 3
